swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API

paths:
  /events/nth_inventory:
    get:
      summary: gets the nth inventory
      operationId: app.get_nth_inventory
      description: gets the nth inventory
      produces:
      - application/json
      parameters:
      - in: query
        name: position
        description: the position
        required: true
        type: integer
      responses:
        200:
          description: search results matching criteria
          schema:
            type: object
            properties:
              inventory:
                type: string
                description: The name of the inventory
              datetime:
                type: string
                format: date-time
                description: When the inventory was added
        400:
          description: invalid input, object invalid
        404:
          description: object not found
  /events/nth_status:
    get:
      summary: gets the nth status
      operationId: app.get_nth_status
      description: gets the nth status
      produces:
      - application/json
      parameters:
      - in: query
        name: start_date
        description: Start Date Filter
        type: string
        format: date-time
        required: true
      - in: query
        name: end_date
        description: End Date Filter
        type: string
        format: date-time
        required: true
      responses:
        200:
          description: current status
          schema:
            type: object
            properties:
              inventory:
                type: string
                description: The status of the inventory
        400:
          description: invalid input, object invalid
        404:
          description: object not found